////////////////////////////////////////////////////////////////////////////
//	Created		: 21.05.2010
//	Author		: Armen Abroyan
//	Copyright (C) GSC Game World - 2010
////////////////////////////////////////////////////////////////////////////

#ifndef XRAY_RENDER_CORE_DX11_DEFINES_H_INCLUDED
#define XRAY_RENDER_CORE_DX11_DEFINES_H_INCLUDED

#include <d3d11shader.h>

#define	SHADER_PARAM_STUB						, NULL, 0

#define	D3DXGetImageInfoFromMemory				D3DX11GetImageInfoFromMemory
#define	D3DXCreateTextureFromMemory				D3DX11CreateTextureFromMemory
#define	D3DXCompileFromMemory					D3DX11CompileFromMemory

typedef	ID3D11VertexShader						ID3DVertexShader;
typedef	ID3D11GeometryShader					ID3DGeometryShader;
typedef	ID3D11PixelShader						ID3DPixelShader;
//typedef	ID3DBlob								ID3DBlob;
//typedef	D3D11_SHADER_MACRO						D3D_SHADER_MACRO;
typedef	ID3D11Query								ID3DQuery;
typedef	D3D11_VIEWPORT							D3D_VIEWPORT;
//typedef	ID3D11Include							ID3DInclude;
typedef	ID3D11Texture2D							ID3DTexture2D;
typedef	ID3D11RenderTargetView					ID3DRenderTargetView;
typedef	ID3D11DepthStencilView					ID3DDepthStencilView;
typedef	ID3D11Resource							ID3DBaseTexture;
typedef	D3D11_TEXTURE2D_DESC					D3D_TEXTURE2D_DESC;
typedef	D3D11_TEXTURE3D_DESC					D3D_TEXTURE3D_DESC;
typedef ID3D11Buffer							ID3DVertexBuffer;
typedef ID3D11Buffer							ID3DIndexBuffer;
typedef ID3D11Buffer							ID3DConstantBuffer;
typedef ID3D11Buffer							ID3DBuffer;
typedef	ID3D11Texture3D							ID3DTexture3D;
typedef	ID3D11SamplerState						ID3DSamplerState;
typedef	ID3D11Device							ID3DDevice;
typedef	ID3D11DeviceContext						ID3DDeviceContext;
typedef	void									ID3DDevice1;
typedef	ID3D11ShaderResourceView				ID3DShaderResourceView;
typedef	ID3D11InputLayout						ID3DInputLayout;

// Render states defines
typedef	ID3D11RasterizerState					ID3DRasterizerState;
typedef	ID3D11DepthStencilState					ID3DDepthStencilState;
typedef	ID3D11BlendState						ID3DBlendState;

typedef	ID3D11ShaderReflection					ID3DShaderReflection;
typedef	ID3D11ShaderReflectionConstantBuffer	ID3DShaderReflectionConstantBuffer;
typedef	ID3D11ShaderReflectionVariable			ID3DShaderReflectionVariable;
typedef	ID3D11ShaderReflectionType				ID3DShaderReflectionType;

typedef	D3D11_RASTERIZER_DESC					D3D_RASTERIZER_DESC;
typedef	D3D11_DEPTH_STENCIL_DESC				D3D_DEPTH_STENCIL_DESC;
typedef	D3D11_BLEND_DESC						D3D_BLEND_DESC;
typedef D3D11_SAMPLER_DESC						D3D_SAMPLER_DESC;

typedef D3D11_SHADER_DESC						D3D_SHADER_DESC;

typedef	D3D11_INPUT_ELEMENT_DESC				D3D_INPUT_ELEMENT_DESC;
//typedef	D3D11_DRIVER_TYPE					D3D_DRIVER_TYPE;

//typedef	D3D11_SHADER_MACRO					D3D_SHADER_MACRO;

typedef	ID3DInclude								ID3D11Include;
#define D3D_INCLUDE_TYPE						D3D10_INCLUDE_TYPE

#define D3DX_IMAGE_INFO							D3DX11_IMAGE_INFO 
#define D3DX_IMAGE_LOAD_INFO					D3DX11_IMAGE_LOAD_INFO

#define D3D_SHADER_DEBUG						D3D10_SHADER_DEBUG
#define D3D_SHADER_PACK_MATRIX_ROW_MAJOR		D3D10_SHADER_PACK_MATRIX_ROW_MAJOR
#define D3D_SHADER_PACK_MATRIX_COLUMN_MAJOR		D3D10_SHADER_PACK_MATRIX_COLUMN_MAJOR
#define D3D_SHADER_PREFER_FLOW_CONTROL			D3D10_SHADER_PREFER_FLOW_CONTROL


#define D3D_CREATE_DEVICE_SINGLETHREADED		D3D11_CREATE_DEVICE_SINGLETHREADED
#define D3D_CREATE_DEVICE_DEBUG					D3D11_CREATE_DEVICE_DEBUG
#define D3D_CREATE_DEVICE_SWITCH_TO_REF			D3D11_CREATE_DEVICE_SWITCH_TO_REF
#define D3D_CREATE_DEVICE_PREVENT_INTERNAL_THREADING_OPTIMIZATIONS		D3D11_CREATE_DEVICE_PREVENT_INTERNAL_THREADING_OPTIMIZATIONS
#define D3D_CREATE_DEVICE_BGRA_SUPPORT			D3D11_CREATE_DEVICE_BGRA_SUPPORT

#define D3DPRESENT_INTERVAL_DEFAULT     		0x00000000L
#define D3DPRESENT_INTERVAL_ONE         		0x00000001L
#define D3DPRESENT_INTERVAL_TWO         		0x00000002L
#define D3DPRESENT_INTERVAL_THREE       		0x00000004L
#define D3DPRESENT_INTERVAL_FOUR        		0x00000008L
#define D3DPRESENT_INTERVAL_IMMEDIATE   		0x80000000L  // Not used in DX10



#define D3D_COMMONSHADER_SAMPLER_SLOT_COUNT		D3D11_COMMONSHADER_SAMPLER_SLOT_COUNT
#define D3D_COMMONSHADER_INPUT_RESOURCE_SLOT_COUNT	16 //D3D11_COMMONSHADER_INPUT_RESOURCE_SLOT_COUNT;


typedef D3D11_COLOR_WRITE_ENABLE				D3D_COLOR_WRITE_ENABLE;

#define	D3D_COLOR_WRITE_ENABLE_RED				D3D11_COLOR_WRITE_ENABLE_RED
#define	D3D_COLOR_WRITE_ENABLE_GREEN			D3D11_COLOR_WRITE_ENABLE_GREEN
#define	D3D_COLOR_WRITE_ENABLE_BLUE				D3D11_COLOR_WRITE_ENABLE_BLUE
#define	D3D_COLOR_WRITE_ENABLE_ALPHA			D3D11_COLOR_WRITE_ENABLE_ALPHA
#define	D3D_COLOR_WRITE_ENABLE_ALL				D3D11_COLOR_WRITE_ENABLE_ALL
#define	D3D_COLOR_WRITE_ENABLE_NONE				D3D_COLOR_WRITE_ENABLE(0)



typedef D3D11_COMPARISON_FUNC					D3D_COMPARISON_FUNC;

#define	D3D_COMPARISON_NEVER					D3D11_COMPARISON_NEVER
#define	D3D_COMPARISON_LESS						D3D11_COMPARISON_LESS
#define	D3D_COMPARISON_EQUAL					D3D11_COMPARISON_EQUAL
#define	D3D_COMPARISON_LESS_EQUAL				D3D11_COMPARISON_LESS_EQUAL
#define	D3D_COMPARISON_GREATER					D3D11_COMPARISON_GREATER
#define	D3D_COMPARISON_NOT_EQUAL				D3D11_COMPARISON_NOT_EQUAL
#define	D3D_COMPARISON_GREATER_EQUAL			D3D11_COMPARISON_GREATER_EQUAL
#define	D3D_COMPARISON_ALWAYS					D3D11_COMPARISON_ALWAYS


typedef D3D11_STENCIL_OP						D3D_STENCIL_OP;

#define	D3D_STENCIL_OP_KEEP						D3D11_STENCIL_OP_KEEP
#define	D3D_STENCIL_OP_ZERO						D3D11_STENCIL_OP_ZERO
#define	D3D_STENCIL_OP_REPLACE					D3D11_STENCIL_OP_REPLACE
#define	D3D_STENCIL_OP_INCR_SAT					D3D11_STENCIL_OP_INCR_SAT
#define	D3D_STENCIL_OP_DECR_SAT					D3D11_STENCIL_OP_DECR_SAT
#define	D3D_STENCIL_OP_INVERT					D3D11_STENCIL_OP_INVERT
#define	D3D_STENCIL_OP_INCR						D3D11_STENCIL_OP_INCR
#define	D3D_STENCIL_OP_DECR						D3D11_STENCIL_OP_DECR


typedef	D3D11_BLEND								D3D_BLEND;

#define D3D_BLEND_ZERO							D3D11_BLEND_ZERO
#define D3D_BLEND_ONE							D3D11_BLEND_ONE
#define D3D_BLEND_SRC_COLOR						D3D11_BLEND_SRC_COLOR
#define D3D_BLEND_INV_SRC_COLOR					D3D11_BLEND_INV_SRC_COLOR	
#define D3D_BLEND_SRC_ALPHA						D3D11_BLEND_SRC_ALPHA	
#define D3D_BLEND_INV_SRC_ALPHA					D3D11_BLEND_INV_SRC_ALPHA	
#define D3D_BLEND_DEST_ALPHA					D3D11_BLEND_DEST_ALPHA	
#define D3D_BLEND_INV_DEST_ALPHA				D3D11_BLEND_INV_DEST_ALPHA	
#define D3D_BLEND_DEST_COLOR					D3D11_BLEND_DEST_COLOR	
#define D3D_BLEND_INV_DEST_COLOR				D3D11_BLEND_INV_DEST_COLOR	
#define D3D_BLEND_SRC_ALPHA_SAT					D3D11_BLEND_SRC_ALPHA_SAT	
#define D3D_BLEND_BLEND_FACTOR					D3D11_BLEND_BLEND_FACTOR	
#define D3D_BLEND_INV_BLEND_FACTOR				D3D11_BLEND_INV_BLEND_FACTOR	
#define D3D_BLEND_SRC1_COLOR					D3D11_BLEND_SRC1_COLOR	
#define D3D_BLEND_INV_SRC1_COLOR				D3D11_BLEND_INV_SRC1_COLOR	
#define D3D_BLEND_SRC1_ALPHA					D3D11_BLEND_SRC1_ALPHA	
#define D3D_BLEND_INV_SRC1_ALPHA				D3D11_BLEND_INV_SRC1_ALPHA	


typedef	D3D11_TEXTURE_ADDRESS_MODE				D3D_TEXTURE_ADDRESS_MODE;

#define	D3D_TEXTURE_ADDRESS_WRAP				D3D11_TEXTURE_ADDRESS_WRAP
#define	D3D_TEXTURE_ADDRESS_MIRROR				D3D11_TEXTURE_ADDRESS_MIRROR
#define	D3D_TEXTURE_ADDRESS_CLAMP				D3D11_TEXTURE_ADDRESS_CLAMP
#define	D3D_TEXTURE_ADDRESS_BORDER				D3D11_TEXTURE_ADDRESS_BORDER
#define	D3D_TEXTURE_ADDRESS_MIRROR_ONCE			D3D11_TEXTURE_ADDRESS_MIRROR_ONCE


typedef D3D11_FILTER							D3D_FILTER;

#define	D3D_FILTER_MIN_MAG_MIP_POINT							D3D11_FILTER_MIN_MAG_MIP_POINT
#define	D3D_FILTER_MIN_MAG_POINT_MIP_LINEAR						D3D11_FILTER_MIN_MAG_POINT_MIP_LINEAR
#define	D3D_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT				D3D11_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT
#define	D3D_FILTER_MIN_POINT_MAG_MIP_LINEAR						D3D11_FILTER_MIN_POINT_MAG_MIP_LINEAR
#define	D3D_FILTER_MIN_LINEAR_MAG_MIP_POINT						D3D11_FILTER_MIN_LINEAR_MAG_MIP_POINT 
#define	D3D_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR				D3D11_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR
#define	D3D_FILTER_MIN_MAG_LINEAR_MIP_POINT						D3D11_FILTER_MIN_MAG_LINEAR_MIP_POINT 
#define	D3D_FILTER_MIN_MAG_MIP_LINEAR							D3D11_FILTER_MIN_MAG_MIP_LINEAR
#define	D3D_FILTER_ANISOTROPIC									D3D11_FILTER_ANISOTROPIC
#define	D3D_FILTER_COMPARISON_MIN_MAG_MIP_POINT					D3D11_FILTER_COMPARISON_MIN_MAG_MIP_POINT
#define	D3D_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR			D3D11_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR
#define	D3D_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT	D3D11_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT
#define	D3D_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR			D3D11_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR
#define	D3D_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT			D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT
#define	D3D_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR 	D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR
#define	D3D_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT			D3D11_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT
#define	D3D_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR				D3D11_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR
#define	D3D_FILTER_COMPARISON_ANISOTROPIC						D3D11_FILTER_COMPARISON_ANISOTROPIC
#define	D3D_FILTER_TEXT_1BIT									D3D11_FILTER_TEXT_1BIT

typedef	D3D11_BUFFER_DESC						D3D_BUFFER_DESC;
typedef	D3D11_SUBRESOURCE_DATA					D3D_SUBRESOURCE_DATA;
typedef D3D11_USAGE								D3D_USAGE;
#define	D3D_USAGE_DEFAULT						D3D11_USAGE_DEFAULT
#define	D3D_USAGE_DYNAMIC						D3D11_USAGE_DYNAMIC
#define	D3D_USAGE_STAGING						D3D11_USAGE_STAGING
#define	D3D_USAGE_IMMUTABLE						D3D11_USAGE_IMMUTABLE

typedef D3D11_BIND_FLAG							D3D_BIND_FLAG;
#define	D3D_BIND_VERTEX_BUFFER					D3D11_BIND_VERTEX_BUFFER
#define	D3D_BIND_INDEX_BUFFER					D3D11_BIND_INDEX_BUFFER
#define	D3D_BIND_CONSTANT_BUFFER				D3D11_BIND_CONSTANT_BUFFER 
#define	D3D_BIND_SHADER_RESOURCE				D3D11_BIND_SHADER_RESOURCE
#define	D3D_BIND_STREAM_OUTPUT					D3D11_BIND_STREAM_OUTPUT 
#define	D3D_BIND_RENDER_TARGET					D3D11_BIND_RENDER_TARGET 
#define	D3D_BIND_DEPTH_STENCIL					D3D11_BIND_DEPTH_STENCIL

typedef D3D11_CPU_ACCESS_FLAG					D3D_CPU_ACCESS_FLAG;
#define	D3D_CPU_ACCESS_WRITE					D3D11_CPU_ACCESS_WRITE 
#define	D3D_CPU_ACCESS_READ						D3D11_CPU_ACCESS_READ 

#define	D3D_STENCIL_OP_KEEP						D3D11_STENCIL_OP_KEEP
#define	D3D_STENCIL_OP_ZERO						D3D11_STENCIL_OP_ZERO
#define	D3D_STENCIL_OP_REPLACE					D3D11_STENCIL_OP_REPLACE
#define	D3D_STENCIL_OP_INCR_SAT					D3D11_STENCIL_OP_INCR_SAT
#define	D3D_STENCIL_OP_DECR_SAT					D3D11_STENCIL_OP_DECR_SAT
#define	D3D_STENCIL_OP_INVERT					D3D11_STENCIL_OP_INVERT
#define	D3D_STENCIL_OP_INCR						D3D11_STENCIL_OP_INCR
#define	D3D_STENCIL_OP_DECR						D3D11_STENCIL_OP_DECR

#define	D3D_BLEND_ZERO							D3D11_BLEND_ZERO
#define	D3D_BLEND_ONE							D3D11_BLEND_ONE
#define	D3D_BLEND_SRC_COLOR						D3D11_BLEND_SRC_COLOR
#define	D3D_BLEND_INV_SRC_COLOR					D3D11_BLEND_INV_SRC_COLOR
#define	D3D_BLEND_SRC_ALPHA						D3D11_BLEND_SRC_ALPHA
#define	D3D_BLEND_INV_SRC_ALPHA					D3D11_BLEND_INV_SRC_ALPHA
#define	D3D_BLEND_DEST_ALPHA					D3D11_BLEND_DEST_ALPHA
#define	D3D_BLEND_INV_DEST_ALPHA				D3D11_BLEND_INV_DEST_ALPHA
#define	D3D_BLEND_DEST_COLOR					D3D11_BLEND_DEST_COLOR
#define	D3D_BLEND_INV_DEST_COLOR				D3D11_BLEND_INV_DEST_COLOR
#define	D3D_BLEND_SRC_ALPHA_SAT					D3D11_BLEND_SRC_ALPHA_SAT
#define	D3D_BLEND_BLEND_FACTOR					D3D11_BLEND_BLEND_FACTOR
#define	D3D_BLEND_INV_BLEND_FACTOR				D3D11_BLEND_INV_BLEND_FACTOR
#define	D3D_BLEND_SRC1_COLOR					D3D11_BLEND_SRC1_COLOR
#define	D3D_BLEND_INV_SRC1_COLOR				D3D11_BLEND_INV_SRC1_COLOR
#define	D3D_BLEND_SRC1_ALPHA					D3D11_BLEND_SRC1_ALPHA
#define	D3D_BLEND_INV_SRC1_ALPHA				D3D11_BLEND_INV_SRC1_ALPHA


typedef D3D11_FORMAT_SUPPORT								D3D_FORMAT_SUPPORT;
#define	D3D11_FORMAT_SUPPORT_BUFFER							D3D11_FORMAT_SUPPORT_BUFFER
#define	D3D11_FORMAT_SUPPORT_IA_VERTEX_BUFFER				D3D11_FORMAT_SUPPORT_IA_VERTEX_BUFFER
#define	D3D11_FORMAT_SUPPORT_IA_INDEX_BUFFER				D3D11_FORMAT_SUPPORT_IA_INDEX_BUFFER 
#define	D3D11_FORMAT_SUPPORT_SO_BUFFER						D3D11_FORMAT_SUPPORT_SO_BUFFER 
#define	D3D11_FORMAT_SUPPORT_TEXTURE1D						D3D11_FORMAT_SUPPORT_TEXTURE1D 
#define	D3D11_FORMAT_SUPPORT_TEXTURE2D						D3D11_FORMAT_SUPPORT_TEXTURE2D 
#define	D3D11_FORMAT_SUPPORT_TEXTURE3D						D3D11_FORMAT_SUPPORT_TEXTURE3D 
#define	D3D11_FORMAT_SUPPORT_TEXTURECUBE					D3D11_FORMAT_SUPPORT_TEXTURECUBE
#define	D3D11_FORMAT_SUPPORT_SHADER_LOAD					D3D11_FORMAT_SUPPORT_SHADER_LOAD
#define	D3D11_FORMAT_SUPPORT_SHADER_SAMPLE					D3D11_FORMAT_SUPPORT_SHADER_SAMPLE
#define	D3D11_FORMAT_SUPPORT_SHADER_SAMPLE_COMPARISON		D3D11_FORMAT_SUPPORT_SHADER_SAMPLE_COMPARISON
#define	D3D11_FORMAT_SUPPORT_SHADER_SAMPLE_MONO_TEXT		D3D11_FORMAT_SUPPORT_SHADER_SAMPLE_MONO_TEXT
#define	D3D11_FORMAT_SUPPORT_MIP							D3D11_FORMAT_SUPPORT_MIP
#define	D3D11_FORMAT_SUPPORT_MIP_AUTOGEN					D3D11_FORMAT_SUPPORT_MIP_AUTOGEN 
#define	D3D11_FORMAT_SUPPORT_RENDER_TARGET					D3D11_FORMAT_SUPPORT_RENDER_TARGET 
#define	D3D11_FORMAT_SUPPORT_BLENDABLE						D3D11_FORMAT_SUPPORT_BLENDABLE 
#define	D3D11_FORMAT_SUPPORT_DEPTH_STENCIL					D3D11_FORMAT_SUPPORT_DEPTH_STENCIL 
#define	D3D11_FORMAT_SUPPORT_CPU_LOCKABLE					D3D11_FORMAT_SUPPORT_CPU_LOCKABLE 
#define	D3D11_FORMAT_SUPPORT_MULTISAMPLE_RESOLVE			D3D11_FORMAT_SUPPORT_MULTISAMPLE_RESOLVE 
#define	D3D11_FORMAT_SUPPORT_DISPLAY						D3D11_FORMAT_SUPPORT_DISPLAY 
#define	D3D11_FORMAT_SUPPORT_CAST_WITHIN_BIT_LAYOUT			D3D11_FORMAT_SUPPORT_CAST_WITHIN_BIT_LAYOUT 
#define	D3D11_FORMAT_SUPPORT_MULTISAMPLE_RENDERTARGET		D3D11_FORMAT_SUPPORT_MULTISAMPLE_RENDERTARGET 
#define	D3D11_FORMAT_SUPPORT_MULTISAMPLE_LOAD				D3D11_FORMAT_SUPPORT_MULTISAMPLE_LOAD 
#define	D3D11_FORMAT_SUPPORT_SHADER_GATHER					D3D11_FORMAT_SUPPORT_SHADER_GATHER 


typedef D3D11_FILL_MODE					D3D_FILL_MODE;
#define	D3D_FILL_WIREFRAME				D3D11_FILL_WIREFRAME
#define	D3D_FILL_SOLID					D3D11_FILL_SOLID


typedef D3D11_CULL_MODE					D3D_CULL_MODE;
#define	D3D_CULL_NONE					D3D11_CULL_NONE 
#define	D3D_CULL_FRONT					D3D11_CULL_FRONT
#define	D3D_CULL_BACK					D3D11_CULL_BACK 


typedef D3D11_DEPTH_WRITE_MASK			D3D_DEPTH_WRITE_MASK;
#define	D3D_DEPTH_WRITE_MASK_ZERO		D3D11_DEPTH_WRITE_MASK_ZERO
#define	D3D_DEPTH_WRITE_MASK_ALL		D3D11_DEPTH_WRITE_MASK_ALL 


typedef D3D11_BLEND_OP					D3D_BLEND_OP;
#define	D3D_BLEND_OP_ADD				D3D11_BLEND_OP_ADD 
#define	D3D_BLEND_OP_SUBTRACT			D3D11_BLEND_OP_SUBTRACT 
#define	D3D_BLEND_OP_REV_SUBTRACT		D3D11_BLEND_OP_REV_SUBTRACT 
#define	D3D_BLEND_OP_MIN				D3D11_BLEND_OP_MIN 
#define	D3D_BLEND_OP_MAX				D3D11_BLEND_OP_MAX 

typedef D3D11_CBUFFER_TYPE				D3D_CBUFFER_TYPE;
#define	D3D_CT_CBUFFER					D3D11_CT_CBUFFER;
#define	D3D_CT_TBUFFER					D3D11_CT_CBUFFER;

typedef	D3D11_SHADER_TYPE_DESC			D3D_SHADER_TYPE_DESC;
typedef	D3D11_SHADER_BUFFER_DESC		D3D_SHADER_BUFFER_DESC;
typedef	D3D11_SHADER_VARIABLE_DESC		D3D_SHADER_VARIABLE_DESC;
typedef	D3D11_SHADER_INPUT_BIND_DESC	D3D_SHADER_INPUT_BIND_DESC;

typedef D3D11_MAP						D3D_MAP;
#define	D3D_MAP_READ					D3D11_MAP_READ 
#define	D3D_MAP_WRITE					D3D11_MAP_WRITE
#define	D3D_MAP_READ_WRITE				D3D11_MAP_READ_WRITE 
#define	D3D_MAP_WRITE_DISCARD			D3D11_MAP_WRITE_DISCARD 
#define	D3D_MAP_WRITE_NO_OVERWRITE		D3D11_MAP_WRITE_NO_OVERWRITE 

//typedef D3D11_SHADER_INPUT_TYPE						D3D_SHADER_INPUT_TYPE;

#define	D3D11_SIT_CBUFFER							D3D11_SIT_CBUFFER
#define	D3D11_SIT_TBUFFER							D3D11_SIT_TBUFFER
#define	D3D11_SIT_TEXTURE							D3D11_SIT_TEXTURE
#define	D3D11_SIT_SAMPLER							D3D11_SIT_SAMPLER
#define	D3D11_SIT_UAV_RWTYPED						D3D11_SIT_UAV_RWTYPED
#define	D3D11_SIT_STRUCTURED						D3D11_SIT_STRUCTURED
#define	D3D11_SIT_UAV_RWSTRUCTURED					D3D11_SIT_UAV_RWSTRUCTURED
#define	D3D11_SIT_BYTEADDRESS						D3D11_SIT_BYTEADDRESS
#define	D3D11_SIT_UAV_RWBYTEADDRESS					D3D11_SIT_UAV_RWBYTEADDRESS
#define	D3D11_SIT_UAV_APPEND_STRUCTURED				D3D11_SIT_UAV_APPEND_STRUCTURED
#define	D3D11_SIT_UAV_CONSUME_STRUCTURED			D3D11_SIT_UAV_CONSUME_STRUCTURED
#define	D3D11_SIT_UAV_RWSTRUCTURED_WITH_COUNTER		D3D11_SIT_UAV_RWSTRUCTURED_WITH_COUNTER

typedef D3D11_SHADER_RESOURCE_VIEW_DESC			D3D_SHADER_RESOURCE_VIEW_DESC;
typedef D3D11_DEPTH_STENCIL_VIEW_DESC			D3D_DEPTH_STENCIL_VIEW_DESC;

typedef D3D11_RENDER_TARGET_VIEW_DESC			D3D_RENDER_TARGET_VIEW_DESC;
#define D3D_RTV_DIMENSION_TEXTURE2DARRAY		D3D11_RTV_DIMENSION_TEXTURE2DARRAY

typedef D3D11_RESOURCE_DIMENSION				D3D_RESOURCE_DIMENSION;
#define D3D_RESOURCE_DIMENSION_UNKNOWN			D3D11_RESOURCE_DIMENSION_UNKNOWN
#define D3D_RESOURCE_DIMENSION_BUFFER			D3D11_RESOURCE_DIMENSION_BUFFER
#define D3D_RESOURCE_DIMENSION_TEXTURE1D		D3D11_RESOURCE_DIMENSION_TEXTURE1D
#define D3D_RESOURCE_DIMENSION_TEXTURE2D		D3D11_RESOURCE_DIMENSION_TEXTURE2D
#define D3D_RESOURCE_DIMENSION_TEXTURE3D		D3D11_RESOURCE_DIMENSION_TEXTURE3D


typedef D3D11_RESOURCE_MISC_FLAG				D3D_RESOURCE_MISC_FLAG;
#define D3D_RESOURCE_MISC_GENERATE_MIPS			D3D11_RESOURCE_MISC_GENERATE_MIPS
#define D3D_RESOURCE_MISC_SHARED				D3D11_RESOURCE_MISC_SHARED
#define D3D_RESOURCE_MISC_TEXTURECUBE			D3D11_RESOURCE_MISC_TEXTURECUBE
#define D3D_RESOURCE_MISC_SHARED_KEYEDMUTEX		D3D11_RESOURCE_MISC_SHARED_KEYEDMUTEX
#define D3D_RESOURCE_MISC_GDI_COMPATIBLE		D3D11_RESOURCE_MISC_GDI_COMPATIBLE

typedef D3D11_SRV_DIMENSION						D3D_SRV_DIMENSION;
#define D3D_SRV_DIMENSION_UNKNOWN				D3D11_SRV_DIMENSION_UNKNOWN
#define D3D_SRV_DIMENSION_BUFFER				D3D11_SRV_DIMENSION_BUFFER
#define D3D_SRV_DIMENSION_TEXTURE1D				D3D11_SRV_DIMENSION_TEXTURE1D
#define D3D_SRV_DIMENSION_TEXTURE1DARRAY		D3D11_SRV_DIMENSION_TEXTURE1DARRAY
#define D3D_SRV_DIMENSION_TEXTURE2D				D3D11_SRV_DIMENSION_TEXTURE2D
#define D3D_SRV_DIMENSION_TEXTURE2DARRAY		D3D11_SRV_DIMENSION_TEXTURE2DARRAY	
#define D3D_SRV_DIMENSION_TEXTURE2DMS			D3D11_SRV_DIMENSION_TEXTURE2DMS	
#define D3D_SRV_DIMENSION_TEXTURE2DMSARRAY		D3D11_SRV_DIMENSION_TEXTURE2DMSARRAY
#define D3D_SRV_DIMENSION_TEXTURE3D				D3D11_SRV_DIMENSION_TEXTURE3D
#define D3D_SRV_DIMENSION_TEXTURECUBE			D3D11_SRV_DIMENSION_TEXTURECUBE

#define D3D_RTV_DIMENSION_TEXTURE2DMS			D3D11_RTV_DIMENSION_TEXTURE2DMS

#define	D3D_REQ_TEXTURE2D_U_OR_V_DIMENSION		D3D11_REQ_TEXTURE2D_U_OR_V_DIMENSION

typedef D3D11_DSV_DIMENSION						D3D_DSV_DIMENSION;
#define D3D_DSV_DIMENSION_UNKNOWN				D3D11_DSV_DIMENSION_UNKNOWN	        
#define D3D_DSV_DIMENSION_TEXTURE1D				D3D11_DSV_DIMENSION_TEXTURE1D
#define D3D_DSV_DIMENSION_TEXTURE1DARRAY		D3D11_DSV_DIMENSION_TEXTURE1DARRAY
#define D3D_DSV_DIMENSION_TEXTURE2D				D3D11_DSV_DIMENSION_TEXTURE2D	
#define D3D_DSV_DIMENSION_TEXTURE2DARRAY		D3D11_DSV_DIMENSION_TEXTURE2DARRAY	
#define D3D_DSV_DIMENSION_TEXTURE2DMS			D3D11_DSV_DIMENSION_TEXTURE2DMS	
#define D3D_DSV_DIMENSION_TEXTURE2DMSARRAY		D3D11_DSV_DIMENSION_TEXTURE2DMSARRAY


typedef D3D11_INPUT_CLASSIFICATION				D3D_INPUT_CLASSIFICATION;

#define D3D_INPUT_PER_VERTEX_DATA				D3D11_INPUT_PER_VERTEX_DATA
#define D3D_INPUT_PER_INSTANCE_DATA				D3D11_INPUT_PER_VERTEX_DATA

typedef D3D11_PRIMITIVE_TOPOLOGY					D3D_PRIMITIVE_TOPOLOGY;
#define D3D_PRIMITIVE_TOPOLOGY_UNDEFINED			D3D11_PRIMITIVE_TOPOLOGY_UNDEFINED		
#define D3D_PRIMITIVE_TOPOLOGY_POINTLIST			D3D11_PRIMITIVE_TOPOLOGY_POINTLIST		
#define D3D_PRIMITIVE_TOPOLOGY_LINELIST			D3D11_PRIMITIVE_TOPOLOGY_LINELIST		
#define D3D_PRIMITIVE_TOPOLOGY_LINESTRIP			D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP		
#define D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST		D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST	
#define D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP		D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP	
#define D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ		D3D11_PRIMITIVE_TOPOLOGY_LINELIST_ADJ 
#define D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ		D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ 
#define D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ	D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ
#define D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ	D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ


typedef D3D11_CLEAR_FLAG					D3D_CLEAR_FLAG;

#define D3D_CLEAR_DEPTH						D3D11_CLEAR_DEPTH
#define D3D_CLEAR_STENCIL					D3D11_CLEAR_STENCIL

typedef D3D11_BOX							D3D_BOX;

typedef ID3D11Counter ID3DCounter;
typedef D3D11_COUNTER_DESC D3D_COUNTER_DESC;

#define D3D_COUNTER D3D11_COUNTER

#define D3D_COUNTER_TYPE D3D11_COUNTER_TYPE
#define D3D_COUNTER_TYPE D3D11_COUNTER_TYPE
#define D3D_COUNTER_INFO D3D11_COUNTER_INFO

#define D3D_COUNTER_GPU_IDLE (0)
#define D3D_COUNTER_VERTEX_PROCESSING (0)
#define D3D_COUNTER_GEOMETRY_PROCESSING (0)
#define D3D_COUNTER_PIXEL_PROCESSING (0)
#define D3D_COUNTER_OTHER_GPU_PROCESSING (0)
#define D3D_COUNTER_HOST_ADAPTER_BANDWIDTH_UTILIZATION (0)
#define D3D_COUNTER_LOCAL_VIDMEM_BANDWIDTH_UTILIZATION (0)
#define D3D_COUNTER_VERTEX_THROUGHPUT_UTILIZATION (0)
#define D3D_COUNTER_TRIANGLE_SETUP_THROUGHPUT_UTILIZATION (0)
#define D3D_COUNTER_FILLRATE_THROUGHPUT_UTILIZATION (0)
#define D3D_COUNTER_VS_MEMORY_LIMITED (0)
#define D3D_COUNTER_VS_COMPUTATION_LIMITED (0)
#define D3D_COUNTER_GS_MEMORY_LIMITED (0)
#define D3D_COUNTER_GS_COMPUTATION_LIMITED (0)
#define D3D_COUNTER_PS_MEMORY_LIMITED (0)
#define D3D_COUNTER_PS_COMPUTATION_LIMITED (0)
#define D3D_COUNTER_POST_TRANSFORM_CACHE_HIT_RATE (0)
#define D3D_COUNTER_TEXTURE_CACHE_HIT_RATE (0)
#define D3D_COUNTER_DEVICE_DEPENDENT_0 D3D11_COUNTER_DEVICE_DEPENDENT_0

#define D3D_COUNTER_TYPE_FLOAT32 D3D11_COUNTER_TYPE_FLOAT32
#define D3D_COUNTER_TYPE_UINT16 D3D11_COUNTER_TYPE_UINT16
#define D3D_COUNTER_TYPE_UINT32 D3D11_COUNTER_TYPE_UINT32
#define D3D_COUNTER_TYPE_UINT64 D3D11_COUNTER_TYPE_UINT64

typedef D3D11_QUERY_DESC D3D_QUERY_DESC;
#define D3D_QUERY_TIMESTAMP_DISJOINT D3D11_QUERY_TIMESTAMP_DISJOINT
#define D3D_QUERY_TIMESTAMP D3D11_QUERY_TIMESTAMP
#define D3D_QUERY_DATA_TIMESTAMP_DISJOINT D3D11_QUERY_DATA_TIMESTAMP_DISJOINT

#define D3D_SIMULTANEOUS_RENDER_TARGET_COUNT D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT

#endif // #ifndef XRAY_RENDER_CORE_DX11_DEFINES_H_INCLUDED