//----------------------------------------------------------------------------
void p_PassThrough3
(
    in float3  kInPixelColor : COLOR,
    out float4 kPixelColor : COLOR)
{
    kPixelColor.rgb = kInPixelColor;
    kPixelColor.a = 1.0f;
}
//----------------------------------------------------------------------------
void p_PassThrough4
(
    in float4  kInPixelColor : COLOR,
    out float4 kPixelColor : COLOR)
{
    kPixelColor = kInPixelColor;
}
//----------------------------------------------------------------------------
